spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
#  session:
#    timeout: 60
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/test
        registration:
          keycloak:
            provider: keycloak
            client-id: oauth-client
            client-secret: secret
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
              - roles
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        - id: test-app
          uri: http://localhost:8085/
          predicates:
            - Path=/test/**
            - Method= GET
          filters:
            - CustomHeaderFilter
            - TokenRelay=
